### ISSUE TITLE
About Equimic

### ISSUE THREAD

**Issue by korbosoft** [Equicord/Equimic#1]
unless you are changing more than the name, there is no real reason to fork venmic

**Comment by korbosoft** [comment]
nvm

**Comment by verysillycat** [comment]
![image](https://github.com/user-attachments/assets/90b7b7a2-d725-4307-8b37-b2ebbbe1ae85)

**Comment by thororen1234** [comment]
> unless you are changing more than the name, there is no real reason to fork venmic

this is really just a screw around fork and has the static building added back because someone asked for it and it was denied for venmic.

**Comment by thororen1234** [comment]
I do agree this shouldn't exist at all and I don't want to even have this repo at all but I'm going to till there is a better way of doing static on venmic
.

**Comment by korbosoft** [comment]
> ![image](https://private-user-images.githubusercontent.com/126973723/365473203-90b7b7a2-d725-4307-8b37-b2ebbbe1ae85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNzY0OTIsIm5iZiI6MTcyNzI3NjE5MiwicGF0aCI6Ii8xMjY5NzM3MjMvMzY1NDczMjAzLTkwYjdiN2EyLWQ3MjUtNDMwNy04YjM3LWIyZWJiYmUxYWU4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNVQxNDU2MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MWZkNWVlMDMwZTBjYjk3MzExMmFmMjRhYWE5MzlkNGZiNjIxZGQ5NzU2MWYzMDgyNzRlNTc4YTIxYWMzMzgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.IIUM5op9JhG6Co-PdQxJFcGZcig-yzKmDcXMS93UCRE)

it worked
